---
kind: pipeline
name: Test
platform:
  os: linux
  arch: amd64

steps:
- name: lint
  image: golangci/golangci-lint:v1.37.1
  # libsystemd-dev is required for cgo
  commands:
  - apt-get update -y && apt-get install -y libsystemd-dev
  - make lint

# - name: test
#   image: ubuntu
#   volumes:
#   - name: docker
#     path: /var/run/docker.sock
#   commands:
#   - apt-get update  && apt-get install -y libsystemd-dev
#   - mkdir -p /usr/local/go/bin
#   - wget https://golang.org/dl/go1.16.5.linux-amd64.tar.gz
#   - tar -C /usr/local -xzf go1.16.5.linux-amd64.tar.gz
#   - export PATH=$PATH:/usr/local/go/bin
#   - make cmd/agent/agent cmd/agentctl/agentctl
#   - make test
#   - RELEASE_TAG=v0.0.0 make test-packages


- name: test-ubuntu
  image: ubuntu
  #volumes:
  #- name: docker
  #  path: /var/run/docker.sock
  commands:
  - export DEBIAN_FRONTEND=noninteractive  
  - dpkg --add-architecture i386 
  - apt-get update -y && apt-get install -y $(grep -vE "^\s*#" ./.drone/packages.list  | tr "\n" " ") -y 
  - gem install --no-document fpm
  - mkdir -p /usr/local/go/bin
  - wget https://golang.org/dl/go1.16.5.linux-amd64.tar.gz
  - tar -C /usr/local -xzf go1.16.5.linux-amd64.tar.gz
  - rm go1.16.5.linux-amd64.tar.gz
  - export PATH=$PATH:/usr/local/go/bin
  - apt-get clean && rm -rf /var/lib/apt/lists/*
  # - make BUILD_IN_CONTAINER=false cmd/agent/agent
  - make BUILD_IN_CONTAINER=false cmd/agent/agent cmd/agentctl/agentctl
  - make BUILD_IN_CONTAINER=false dist
  - make BUILD_IN_CONTAINER=false RELEASE_TAG=v0.0.0 BUILD_IN_CONTAINER=false test-packages
  # - make cmd/agentctl/agentctl
  # - make test
  # - RELEASE_TAG=v0.0.0 make test-packages

#volumes:
#- name: docker
#  host: 
#    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: Containerize
platform:
  os: linux
  arch: amd64

steps:
- name: Build Agent Container
  image: docker
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - apk update && apk add make bash wget git qemu
  - wget https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64
  - mkdir -p ~/.docker/cli-plugins 
  - cp buildx-v0.5.1.linux-amd64 ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker buildx create --use
  - CROSS_BUILD=true RELEASE_BUILD=true make agent-image
- name: Build Agentctl Container
  image: docker
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - apk update && apk add make bash wget git qemu
  - wget https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64
  - mkdir -p ~/.docker/cli-plugins 
  - cp buildx-v0.5.1.linux-amd64 ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker buildx create --use
  - CROSS_BUILD=true RELEASE_BUILD=true make agentctl-image

volumes:
- name: docker
  host: 
    path: /var/run/docker.sock
